name: Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-gcc:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - run: apt-get install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang 
        - run: make
        - run: ./bin/shove ./tests/add
        - run: make clean

    build-clang:

        runs-on: ubuntu-latest

        env:
            CC: clang

        steps:
        - uses: actions/checkout@v3
        - run: apt-get install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python3-clang 
        - run: make
        - run: ./bin/shove ./tests/add
        - run: make clean
