name: Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-gcc:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - run: sudo apt-get install llvm
        - run: make
        - run: ./bin/shove ./tests/add -v --emit-llvm=./bin/%.ll -o ./bin/test-add
        - run: make clean

    build-clang:

        runs-on: ubuntu-latest

        env:
            CC: clang

        steps:
        - uses: actions/checkout@v3
        - run: sudo apt-get install llvm
        - run: make
        - run: ./bin/shove ./tests/add -v --emit-llvm=./bin/%.ll -o ./bin/test-add
        - run: make clean
